//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try font.validate()
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `Proxima-Nova-Alt-Bold.otf`.
    static let proximaNovaAltBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Proxima-Nova-Alt-Bold", pathExtension: "otf")
    /// Resource file `Proxima-Nova-Bold.otf`.
    static let proximaNovaBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Proxima-Nova-Bold", pathExtension: "otf")
    /// Resource file `ProximaNovaAltRegular.ttf`.
    static let proximaNovaAltRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "ProximaNovaAltRegular", pathExtension: "ttf")

    /// `bundle.url(forResource: "Proxima-Nova-Alt-Bold", withExtension: "otf")`
    static func proximaNovaAltBoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.proximaNovaAltBoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Proxima-Nova-Bold", withExtension: "otf")`
    static func proximaNovaBoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.proximaNovaBoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "ProximaNovaAltRegular", withExtension: "ttf")`
    static func proximaNovaAltRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.proximaNovaAltRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.font` struct is generated, and contains static references to 3 fonts.
  struct font: Rswift.Validatable {
    /// Font `ProximaNova-Bold`.
    static let proximaNovaBold = Rswift.FontResource(fontName: "ProximaNova-Bold")
    /// Font `ProximaNovaA-Bold`.
    static let proximaNovaABold = Rswift.FontResource(fontName: "ProximaNovaA-Bold")
    /// Font `ProximaNovaA-Regular`.
    static let proximaNovaARegular = Rswift.FontResource(fontName: "ProximaNovaA-Regular")

    /// `UIFont(name: "ProximaNova-Bold", size: ...)`
    static func proximaNovaBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: proximaNovaBold, size: size)
    }

    /// `UIFont(name: "ProximaNovaA-Bold", size: ...)`
    static func proximaNovaABold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: proximaNovaABold, size: size)
    }

    /// `UIFont(name: "ProximaNovaA-Regular", size: ...)`
    static func proximaNovaARegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: proximaNovaARegular, size: size)
    }

    static func validate() throws {
      if R.font.proximaNovaBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'ProximaNova-Bold' could not be loaded, is 'Proxima-Nova-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.proximaNovaABold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'ProximaNovaA-Bold' could not be loaded, is 'Proxima-Nova-Alt-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.proximaNovaARegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'ProximaNovaA-Regular' could not be loaded, is 'ProximaNovaAltRegular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 4 images.
  struct image {
    /// Image `Freshhhhhh`.
    static let freshhhhhh = Rswift.ImageResource(bundle: R.hostingBundle, name: "Freshhhhhh")
    /// Image `hotel`.
    static let hotel = Rswift.ImageResource(bundle: R.hostingBundle, name: "hotel")
    /// Image `image_1364_0`.
    static let image_1364_0 = Rswift.ImageResource(bundle: R.hostingBundle, name: "image_1364_0")
    /// Image `images (1)`.
    static let images1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "images (1)")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Freshhhhhh", bundle: ..., traitCollection: ...)`
    static func freshhhhhh(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.freshhhhhh, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "hotel", bundle: ..., traitCollection: ...)`
    static func hotel(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.hotel, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "image_1364_0", bundle: ..., traitCollection: ...)`
    static func image_1364_0(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.image_1364_0, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "images (1)", bundle: ..., traitCollection: ...)`
    static func images1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.images1, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
